[build]
command = "pnpm run build"
publish = "packages/client/dist"
functions = "packages/client/.netlify/functions"

# Production deployment (main branch)
[context.production]
[context.production.environment]
VITE_API_URL = "${URL}/api"
VITE_ENV = "prod"

# Deploy previews (pull requests)
[context.deploy-preview]
[context.deploy-preview.environment]
VITE_API_URL = "${DEPLOY_URL}/api"
VITE_ENV = "staging"

# Branch deploys (non-main branches)
[context.branch-deploy]
[context.branch-deploy.environment]
VITE_API_URL = "${DEPLOY_URL}/api"
VITE_ENV = "staging"

# Development context
[context.dev]
[context.dev.environment]
VITE_API_URL = "http://localhost:3000/api"
VITE_ENV = "dev"

# Function settings for serverless optimization
[functions]
node_bundler = "esbuild"

[build.environment]
NODE_OPTIONS = "--max-old-space-size=1024"
PNPM_VERSION = "8"

# Headers for better performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/api/*"
[headers.values]
Cache-Control = "no-cache"
