/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResponsesRouteImport } from './routes/responses'
import { Route as QuizTakerRouteImport } from './routes/quiz-taker'
import { Route as QuizEditorRouteImport } from './routes/quiz-editor'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ExampleRouteImport } from './routes/example'
import { Route as EnginesRouteImport } from './routes/engines'
import { Route as IndexRouteImport } from './routes/index'
import { ServerRoute as ApiSplatServerRouteImport } from './routes/api/$'

const rootServerRouteImport = createServerRootRoute()

const ResponsesRoute = ResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizTakerRoute = QuizTakerRouteImport.update({
  id: '/quiz-taker',
  path: '/quiz-taker',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizEditorRoute = QuizEditorRouteImport.update({
  id: '/quiz-editor',
  path: '/quiz-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleRoute = ExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => rootRouteImport,
} as any)
const EnginesRoute = EnginesRouteImport.update({
  id: '/engines',
  path: '/engines',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatServerRoute = ApiSplatServerRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/engines': typeof EnginesRoute
  '/example': typeof ExampleRoute
  '/playground': typeof PlaygroundRoute
  '/quiz': typeof QuizRoute
  '/quiz-editor': typeof QuizEditorRoute
  '/quiz-taker': typeof QuizTakerRoute
  '/responses': typeof ResponsesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/engines': typeof EnginesRoute
  '/example': typeof ExampleRoute
  '/playground': typeof PlaygroundRoute
  '/quiz': typeof QuizRoute
  '/quiz-editor': typeof QuizEditorRoute
  '/quiz-taker': typeof QuizTakerRoute
  '/responses': typeof ResponsesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/engines': typeof EnginesRoute
  '/example': typeof ExampleRoute
  '/playground': typeof PlaygroundRoute
  '/quiz': typeof QuizRoute
  '/quiz-editor': typeof QuizEditorRoute
  '/quiz-taker': typeof QuizTakerRoute
  '/responses': typeof ResponsesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/engines'
    | '/example'
    | '/playground'
    | '/quiz'
    | '/quiz-editor'
    | '/quiz-taker'
    | '/responses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/engines'
    | '/example'
    | '/playground'
    | '/quiz'
    | '/quiz-editor'
    | '/quiz-taker'
    | '/responses'
  id:
    | '__root__'
    | '/'
    | '/engines'
    | '/example'
    | '/playground'
    | '/quiz'
    | '/quiz-editor'
    | '/quiz-taker'
    | '/responses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnginesRoute: typeof EnginesRoute
  ExampleRoute: typeof ExampleRoute
  PlaygroundRoute: typeof PlaygroundRoute
  QuizRoute: typeof QuizRoute
  QuizEditorRoute: typeof QuizEditorRoute
  QuizTakerRoute: typeof QuizTakerRoute
  ResponsesRoute: typeof ResponsesRoute
}
export interface FileServerRoutesByFullPath {
  '/api/$': typeof ApiSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/$': typeof ApiSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/$': typeof ApiSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/$'
  id: '__root__' | '/api/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiSplatServerRoute: typeof ApiSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/responses': {
      id: '/responses'
      path: '/responses'
      fullPath: '/responses'
      preLoaderRoute: typeof ResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-taker': {
      id: '/quiz-taker'
      path: '/quiz-taker'
      fullPath: '/quiz-taker'
      preLoaderRoute: typeof QuizTakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-editor': {
      id: '/quiz-editor'
      path: '/quiz-editor'
      fullPath: '/quiz-editor'
      preLoaderRoute: typeof QuizEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example': {
      id: '/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engines': {
      id: '/engines'
      path: '/engines'
      fullPath: '/engines'
      preLoaderRoute: typeof EnginesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnginesRoute: EnginesRoute,
  ExampleRoute: ExampleRoute,
  PlaygroundRoute: PlaygroundRoute,
  QuizRoute: QuizRoute,
  QuizEditorRoute: QuizEditorRoute,
  QuizTakerRoute: QuizTakerRoute,
  ResponsesRoute: ResponsesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiSplatServerRoute: ApiSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
